version: 0.2

phases:
  install:
    commands:
      - echo "Installing Nginx..."
      - sudo apt-get update
      - sudo apt-get install nginx -y
  build:
    commands:
      - echo "Copying index.html to Nginx directory..."
      - sudo cp index.html /var/www/html
  post_build:
    commands:
      - echo "Configuring Nginx..."
      - if [ -f nginx.conf ]; then sudo cp nginx.conf /etc/nginx/sites-available/default; else echo "nginx.conf not found!"; exit 1; fi
      - sudo systemctl restart nginx

artifacts:
  files:
    - '**/*'
